{{/* Database Secrets */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-instance.mysql.fullname" . }}-credentials
  labels:
    {{- include "store-instance.mysql.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ include "store-instance.mysql.rootPassword" . | b64enc | quote }}
  password: {{ include "store-instance.mysql.password" . | b64enc | quote }}
---
{{/* WordPress Secrets */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "store-instance.wordpress.fullname" . }}-credentials
  labels:
    {{- include "store-instance.wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ include "store-instance.wordpress.adminPassword" . | b64enc | quote }}
  auth-key: {{ include "store-instance.wordpress.authKey" . | b64enc | quote }}
  secure-auth-key: {{ include "store-instance.wordpress.secureAuthKey" . | b64enc | quote }}
  logged-in-key: {{ include "store-instance.wordpress.loggedInKey" . | b64enc | quote }}
  nonce-key: {{ include "store-instance.wordpress.nonceKey" . | b64enc | quote }}
  auth-salt: {{ include "store-instance.wordpress.authSalt" . | b64enc | quote }}
  secure-auth-salt: {{ include "store-instance.wordpress.secureAuthSalt" . | b64enc | quote }}
  logged-in-salt: {{ include "store-instance.wordpress.loggedInSalt" . | b64enc | quote }}
  nonce-salt: {{ include "store-instance.wordpress.nonceSalt" . | b64enc | quote }}
