{{/* MySQL Service */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "store-instance.mysql.fullname" . }}
  labels:
    {{- include "store-instance.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.database.type }}
  ports:
    - port: {{ .Values.service.database.port }}
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    {{- include "store-instance.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
  clusterIP: None
