{{ if .Values.placeholder.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-placeholder
  namespace: {{ .Values.store.name | default .Release.Name }}
  labels:
    app.kubernetes.io/name: medusa-placeholder
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: medusa-placeholder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: medusa-placeholder
    spec:
      containers:
        - name: placeholder
          image: "nginx:alpine"
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
{{ end }}
